# Generated by Django 3.0.3 on 2020-03-05 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_user_cruise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_passenger',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_sailer',
        ),
    ]
